### ISSUE TITLE
Changing "dayTimeSyncValue" does nothing

### ISSUE THREAD

**Issue by genandnic** [Aang23/RealSerene#2]
I read in the CurseForge comment section that you could invert day/night by setting "dayTimeSyncValue" to 12000, but this seems to have no effect in-game. The sun and moon still appear where they would when the value was set to the default of 6000. The issue persists after reloading the world, and even after restarting the client.

**Comment by Aang23** [comment]
Oh... Just a very little mistake on my side, will be fixed in the next release.
